### ISSUE TITLE
Table cell_distr is either empty or does not exist

### ISSUE THREAD

**Issue by arotem3** [HoloClean/holoclean#105]
While running the example, I keep running into two alternating errors:
After holoclean is done training the repair model, I run into the error:
```
[ERROR] - generating aux_table cell_distr
Traceback (most recent call last):
  File "/home/amit/Documents/holoclean_project/randomDB_sim.py", line 55, in <module>
    hc.repair_errors(featurizers)
  File "holoclean_master/holoclean.py", line 327, in repair_errors
    status, infer_time = self.repair_engine.infer_repairs()
  File "holoclean_master/repair/repair.py", line 49, in infer_repairs
    self.ds.generate_aux_table(AuxTables.cell_distr, distr_df, store=True, index_attrs=['_vid_'])
  File "holoclean_master/dataset/dataset.py", line 150, in generate_aux_table
    self.aux_table[aux_table].store_to_db(self.engine.engine)
  File "holoclean_master/dataset/table.py", line 75, in store_to_db
    self.df.to_sql(self.name, db_conn, if_exists=if_exists, index=index, index_label=index_label)
  File "/home/amit/anaconda3/envs/hc36/lib/python3.6/site-packages/pandas/core/generic.py", line 2663, in to_sql
    method=method,
  File "/home/amit/anaconda3/envs/hc36/lib/python3.6/site-packages/pandas/io/sql.py", line 521, in to_sql
    method=method,
  File "/home/amit/anaconda3/envs/hc36/lib/python3.6/site-packages/pandas/io/sql.py", line 1316, in to_sql
    table.create()
  File "/home/amit/anaconda3/envs/hc36/lib/python3.6/site-packages/pandas/io/sql.py", line 648, in create
    self.pd_sql.drop_table(self.name, self.schema)
  File "/home/amit/anaconda3/envs/hc36/lib/python3.6/site-packages/pandas/io/sql.py", line 1363, in drop_table
    self.meta.reflect(only=[table_name], schema=schema)
  File "/home/amit/anaconda3/envs/hc36/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 4159, in reflect
    Table(name, self, **reflect_opts)
  File "/home/amit/anaconda3/envs/hc36/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 469, in __new__
    metadata._remove_table(name, schema)
  File "/home/amit/anaconda3/envs/hc36/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/amit/anaconda3/envs/hc36/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 277, in reraise
    raise value
  File "/home/amit/anaconda3/envs/hc36/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 464, in __new__
    table._init(name, metadata, *args, **kw)
  File "/home/amit/anaconda3/envs/hc36/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 552, in _init
    metadata, autoload_with, include_columns, _extend_on=_extend_on
  File "/home/amit/anaconda3/envs/hc36/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 574, in _autoload
    _extend_on=_extend_on,
  File "/home/amit/anaconda3/envs/hc36/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1596, in run_callable
    return callable_(self, *args, **kwargs)
  File "/home/amit/anaconda3/envs/hc36/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 415, in reflecttable
    table, include_columns, exclude_columns, **opts
  File "/home/amit/anaconda3/envs/hc36/lib/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 639, in reflecttable
    raise exc.NoSuchTableError(table.name)
sqlalchemy.exc.NoSuchTableError: cell_distr
```

One solution I tried is to `drop holo; create holo;` Directly after training the repair model, this leads to:
```
[ERROR] - generating aux_table cell_distr
Traceback (most recent call last):
  File "/home/amit/Documents/holoclean_project/randomDB_sim.py", line 55, in <module>
    hc.repair_errors(featurizers)
  File "holoclean_master/holoclean.py", line 327, in repair_errors
    status, infer_time = self.repair_engine.infer_repairs()
  File "holoclean_master/repair/repair.py", line 49, in infer_repairs
    self.ds.generate_aux_table(AuxTables.cell_distr, distr_df, store=True, index_attrs=['_vid_'])
  File "holoclean_master/dataset/dataset.py", line 152, in generate_aux_table
    self.aux_table[aux_table].create_df_index(index_attrs)
  File "holoclean_master/dataset/table.py", line 90, in create_df_index
    self.df.set_index(attr_list, inplace=True)
  File "/home/amit/anaconda3/envs/hc36/lib/python3.6/site-packages/pandas/core/frame.py", line 4303, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['_vid_'] are in the columns"
```
placing a print statement inside `create_df_index` it is clear that `self.df` is empty, so it is difficult to say exactly what is happening.

**Comment by arotem3** [comment]
It seems that this issue occurs when holoclean eagerly claims 100% accuracy while repairing. The `is_clean` member of `FeaturizedDataset` ends up empty which leads to the construction of an empty table in the `holo` database. The solution, it seems is performing some parameter tuning.

From my debugging, it appears that this happens when there are a lot of errors in the data, but holoclean only detects a small fraction of them.
